// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr1HU7pji8QsZrXz0E78w991CQ0I_GVvk',
    appId: '1:1073045289102:web:5aa71026eeb491f91c71df',
    messagingSenderId: '1073045289102',
    projectId: 'e-vente-dc908',
    authDomain: 'e-vente-dc908.firebaseapp.com',
    storageBucket: 'e-vente-dc908.appspot.com',
    measurementId: 'G-SY7FVM9HEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcHR_JeTyXJLyMUR5S9U8vVttyRg4hzgQ',
    appId: '1:1073045289102:android:ee77217ec90034671c71df',
    messagingSenderId: '1073045289102',
    projectId: 'e-vente-dc908',
    storageBucket: 'e-vente-dc908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZvltWbDfFqzRL0I4M8ZO_KAhAU0iuQA',
    appId: '1:1073045289102:ios:0ff6ad34bdd890dc1c71df',
    messagingSenderId: '1073045289102',
    projectId: 'e-vente-dc908',
    storageBucket: 'e-vente-dc908.appspot.com',
    iosBundleId: 'com.example.proyectoE2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzZvltWbDfFqzRL0I4M8ZO_KAhAU0iuQA',
    appId: '1:1073045289102:ios:7907b59c284ab0561c71df',
    messagingSenderId: '1073045289102',
    projectId: 'e-vente-dc908',
    storageBucket: 'e-vente-dc908.appspot.com',
    iosBundleId: 'com.example.proyectoE2App.RunnerTests',
  );
}
